"""Render a :class:`~dqdl_gen.models.Ruleset` as DQDL text.

Output is deliberately deterministic: the same ruleset always produces byte-identical text,
with no timestamp in the header. That is what makes the golden-file tests meaningful, and it
keeps a regenerated ruleset out of a diff unless something real changed.
"""

from __future__ import annotations

import textwrap

from dqdl_gen import syntax
from dqdl_gen.catalog import Catalog
from dqdl_gen.models import Rule, Ruleset

INDENT = "    "
#: Comments wrap at this width. DQDL comments run to the end of a line, so a long piece of
#: evidence becomes several comment lines rather than one very long one.
COMMENT_WIDTH = 92


def render_rule(rule: Rule) -> str:
    """Render one rule, without its comment."""
    parts = [rule.rule_type]
    parts.extend(syntax.quote(parameter) for parameter in rule.parameters)
    if rule.condition:
        parts.append(rule.condition)
    return " ".join(parts)


def emit(ruleset: Ruleset, catalog: Catalog) -> str:
    """Render a complete ``.dqdl`` document.

    The result always ends with a newline: AWS's lexer only treats ``#`` as a comment when
    the line is newline-terminated, so a file ending mid-comment does not parse.
    """
    lines: list[str] = [*_header(ruleset, catalog), ""]

    if not ruleset.rules:
        lines.append("Rules = []")
        return "\n".join(lines) + "\n"

    lines.append("Rules = [")
    last = len(ruleset.rules) - 1
    for index, rule in enumerate(ruleset.rules):
        if index:
            lines.append("")
        lines.extend(_comment(rule.comment, INDENT))
        separator = "" if index == last else ","
        lines.append(f"{INDENT}{render_rule(rule)}{separator}")
    lines.append("]")
    return "\n".join(lines) + "\n"


def _header(ruleset: Ruleset, catalog: Catalog) -> list[str]:
    profile = ruleset.profile
    rows = (
        f"{profile.row_count:,} rows profiled"
        if not profile.sampled
        else _sampled_description(profile.row_count, profile.total_row_count)
    )
    lines = [
        f"Generated by dqdl-gen from {profile.source_name} ({profile.source_format}).",
        f"{rows}, {profile.column_count} columns. Strictness: {ruleset.strictness.value}.",
        (
            f"Rule types verified against AWS's DQDL parser on {catalog.last_verified}: "
            f"{catalog.grammar_source}"
        ),
        "",
        catalog.disclaimer,
    ]
    rendered: list[str] = []
    for line in lines:
        rendered.extend(_comment(line, "") if line else ["#"])
    return rendered


def _sampled_description(sampled: int, total: int | None) -> str:
    if total is None:
        return f"{sampled:,} rows profiled from a sample (file total unknown)"
    return f"{sampled:,} of {total:,} rows profiled from a sample"


def _comment(text: str, indent: str) -> list[str]:
    """Render text as one or more DQDL comment lines."""
    if not text:
        return [f"{indent}#"]
    width = max(COMMENT_WIDTH - len(indent), 20)
    wrapped = textwrap.wrap(
        " ".join(text.split()),
        width=width,
        break_on_hyphens=False,
        break_long_words=False,
    ) or [""]
    return [f"{indent}# {line}" for line in wrapped]
