"""The command line interface, end to end through Typer's test runner.

Nothing here reaches AWS. The `push` command is covered in test_push.py with a stubbed
client, and never with real credentials.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
import yaml
from typer.testing import CliRunner

from dqdl_gen import __version__
from dqdl_gen.cli import EXIT_BAD_CATALOG, EXIT_INVALID_DQDL, EXIT_OK, EXIT_PUSH_FAILED, app

EXIT_USAGE = 2

runner = CliRunner(env={"COLUMNS": "200", "TERM": "dumb", "NO_COLOR": "1"})


def _run(*args: str) -> Any:
    return runner.invoke(app, list(args))


# ------------------------------------------------------------------------------ basics


def test_version() -> None:
    result = _run("--version")
    assert result.exit_code == EXIT_OK
    assert __version__ in result.stdout


def test_help_states_that_generating_is_local() -> None:
    result = _run("--help")
    assert "no AWS calls" in result.stdout.replace("\n", " ")


def test_bare_invocation_shows_the_commands() -> None:
    result = _run()
    for command in ("profile", "generate", "validate", "rules", "push"):
        assert command in result.stdout


# ----------------------------------------------------------------------------- profile


def test_profile_prints_a_table(orders_csv: Path) -> None:
    result = _run("profile", str(orders_csv))
    assert result.exit_code == EXIT_OK
    assert "order_id" in result.stdout
    assert "customer_note" in result.stdout


def test_profile_json(orders_csv: Path) -> None:
    result = _run("profile", str(orders_csv), "--output", "json")
    assert result.exit_code == EXIT_OK
    payload = json.loads(result.stdout)
    assert payload["row_count"] == 500
    assert payload["column_count"] == 5
    names = [column["name"] for column in payload["columns"]]
    assert names == ["order_id", "status", "region", "amount", "customer_note"]
    amount = next(c for c in payload["columns"] if c["name"] == "amount")
    assert amount["null_count"] == 5
    assert amount["completeness"] == pytest.approx(0.99)


def test_profile_with_a_sample(orders_csv: Path) -> None:
    payload = json.loads(
        _run("profile", str(orders_csv), "--sample", "50", "--output", "json").stdout
    )
    assert payload["row_count"] == 50
    assert payload["sampled"] is True
    assert payload["row_count_is_known"] is False


def test_an_unreadable_file_is_a_usage_error(tmp_path: Path) -> None:
    result = _run("profile", str(tmp_path / "nope.csv"))
    assert result.exit_code == EXIT_USAGE
    assert "file not found" in (result.stdout + result.stderr).replace("\n", " ")


def test_an_unknown_format_is_a_usage_error(tmp_path: Path) -> None:
    target = tmp_path / "data.json"
    target.write_text("{}", encoding="utf-8")
    result = _run("profile", str(target))
    assert result.exit_code == EXIT_USAGE


def test_a_zero_sample_is_a_usage_error(orders_csv: Path) -> None:
    assert _run("profile", str(orders_csv), "--sample", "0").exit_code == EXIT_USAGE


# ---------------------------------------------------------------------------- generate


def test_generate_writes_a_dqdl_file(orders_csv: Path, tmp_path: Path) -> None:
    out = tmp_path / "orders.dqdl"
    result = _run("generate", str(orders_csv), "--out", str(out))
    assert result.exit_code == EXIT_OK
    text = out.read_text(encoding="utf-8")
    assert text.startswith("# Generated by dqdl-gen")
    assert text.endswith("\n")
    assert "Rules = [" in text


def test_generate_defaults_the_output_beside_the_input(tmp_path: Path, orders_csv: Path) -> None:
    copied = tmp_path / "copy.csv"
    copied.write_text(orders_csv.read_text(encoding="utf-8"), encoding="utf-8")
    assert _run("generate", str(copied)).exit_code == EXIT_OK
    assert (tmp_path / "copy.dqdl").is_file()


def test_generate_to_stdout(orders_csv: Path) -> None:
    result = _run("generate", str(orders_csv), "--stdout")
    assert result.exit_code == EXIT_OK
    assert result.stdout.startswith("# Generated by dqdl-gen")


def test_generate_explain_prints_the_profile(orders_csv: Path) -> None:
    result = _run("generate", str(orders_csv), "--stdout", "--explain")
    assert result.exit_code == EXIT_OK
    assert "Distinct" in result.stdout
    assert "Rules = [" in result.stdout


def test_generate_json_carries_rules_and_evidence(orders_csv: Path) -> None:
    result = _run("generate", str(orders_csv), "--output", "json")
    assert result.exit_code == EXIT_OK
    payload = json.loads(result.stdout)
    assert payload["strictness"] == "balanced"
    assert payload["rule_count"] == len(payload["rules"])
    assert payload["dqdl"].endswith("\n")
    for rule in payload["rules"]:
        assert rule["evidence"].strip(), f"{rule['rule_type']} has no evidence"
        assert rule["dqdl"].startswith(rule["rule_type"])


@pytest.mark.parametrize("level", ["strict", "balanced", "lenient"])
def test_every_strictness_level_generates_valid_dqdl(orders_csv: Path, level: str) -> None:
    result = _run("generate", str(orders_csv), "--strictness", level, "--stdout")
    assert result.exit_code == EXIT_OK
    assert f"Strictness: {level}" in result.stdout


def test_an_unknown_strictness_is_a_usage_error(orders_csv: Path) -> None:
    assert _run("generate", str(orders_csv), "--strictness", "paranoid").exit_code == EXIT_USAGE


def test_a_sampled_csv_generates_no_row_count_rule(orders_csv: Path) -> None:
    result = _run("generate", str(orders_csv), "--sample", "100", "--stdout")
    assert "RowCount" not in result.stdout


# ---------------------------------------------------------------------------- validate


def test_validate_accepts_generated_output(orders_csv: Path, tmp_path: Path) -> None:
    out = tmp_path / "orders.dqdl"
    _run("generate", str(orders_csv), "--out", str(out))
    result = _run("validate", str(out))
    assert result.exit_code == EXIT_OK
    assert "is valid" in result.stdout


def test_validate_json(orders_csv: Path, tmp_path: Path) -> None:
    out = tmp_path / "orders.dqdl"
    _run("generate", str(orders_csv), "--out", str(out))
    payload = json.loads(_run("validate", str(out), "--output", "json").stdout)
    assert payload["valid"] is True
    assert payload["rule_count"] > 5
    assert all(rule["line"] > 0 for rule in payload["rules"])


def test_validate_rejects_an_invented_rule_type(tmp_path: Path) -> None:
    target = tmp_path / "bad.dqdl"
    target.write_text("Rules = [ Frobnicate > 1 ]\n", encoding="utf-8")
    result = _run("validate", str(target))
    assert result.exit_code == EXIT_INVALID_DQDL
    assert "not a rule type" in result.stderr


def test_validate_rejects_a_missing_file(tmp_path: Path) -> None:
    assert _run("validate", str(tmp_path / "absent.dqdl")).exit_code == EXIT_USAGE


# ------------------------------------------------------------------------------- rules


def test_rules_lists_the_catalogue() -> None:
    result = _run("rules")
    assert result.exit_code == EXIT_OK
    for name in ("RowCount", "IsPrimaryKey", "ColumnValues", "ColumnDataType"):
        assert name in result.stdout
    assert "docs.aws.amazon.com" in result.stdout
    assert "String is not among them" in result.stdout.replace("\n", " ")


def test_rules_json() -> None:
    payload = json.loads(_run("rules", "--output", "json").stdout)
    assert "String" not in payload["data_types"]
    assert set(payload["strictness"]) == {"strict", "balanced", "lenient"}
    for spec in payload["rule_types"].values():
        assert spec["source"].startswith("https://")


# ------------------------------------------------------------------------ catalog file


def test_a_custom_catalog_is_honoured(
    tmp_path: Path, raw_catalog: dict[str, Any], orders_csv: Path
) -> None:
    raw_catalog["strictness"]["balanced"]["row_count_tolerance"]["value"] = 0.5
    target = tmp_path / "dqdl.yaml"
    target.write_text(yaml.safe_dump(raw_catalog), encoding="utf-8")
    result = _run("generate", str(orders_csv), "--stdout", "--catalog-file", str(target))
    assert result.exit_code == EXIT_OK
    assert "RowCount between 250 and 750" in result.stdout


def test_a_broken_catalog_exits_three(tmp_path: Path, orders_csv: Path) -> None:
    target = tmp_path / "dqdl.yaml"
    target.write_text("schema_version: 1\n", encoding="utf-8")
    result = _run("profile", str(orders_csv), "--catalog-file", str(target))
    assert result.exit_code == EXIT_BAD_CATALOG
    assert "Error reading the catalog" in result.stderr


def test_a_missing_catalog_exits_three(tmp_path: Path) -> None:
    result = _run("rules", "--catalog-file", str(tmp_path / "absent.yaml"))
    assert result.exit_code == EXIT_BAD_CATALOG


# -------------------------------------------------------------------------------- push


def test_push_without_confirm_sends_nothing(orders_csv: Path, tmp_path: Path) -> None:
    """The guard that keeps a write command from writing by accident."""
    out = tmp_path / "orders.dqdl"
    _run("generate", str(orders_csv), "--out", str(out))
    result = _run("push", str(out), "--name", "orders-rules")
    assert result.exit_code == EXIT_PUSH_FAILED
    assert "Refusing to write to AWS without --confirm" in result.stderr
    assert "glue:CreateDataQualityRuleset" in result.stderr


def test_push_rejects_an_invalid_ruleset(tmp_path: Path) -> None:
    """Nothing invalid is ever sent to AWS, even with --confirm."""
    target = tmp_path / "bad.dqdl"
    target.write_text("Rules = [ Frobnicate > 1 ]\n", encoding="utf-8")
    result = _run("push", str(target), "--name", "x", "--confirm")
    assert result.exit_code == EXIT_INVALID_DQDL


def test_push_rejects_a_missing_file(tmp_path: Path) -> None:
    assert _run("push", str(tmp_path / "absent.dqdl"), "--name", "x").exit_code == EXIT_USAGE


def test_push_with_confirm_calls_glue_once(
    orders_csv: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The success path, with the AWS call replaced so nothing leaves the machine."""
    import dqdl_gen.push as push_module

    out = tmp_path / "orders.dqdl"
    _run("generate", str(orders_csv), "--out", str(out))

    seen: list[push_module.PushRequest] = []

    def fake_create(
        request: push_module.PushRequest, client: object | None = None
    ) -> push_module.PushResult:
        seen.append(request)
        return push_module.PushResult(name=request.name, region="eu-west-2")

    monkeypatch.setattr(push_module, "create_ruleset", fake_create)
    result = _run(
        "push",
        str(out),
        "--name",
        "orders-rules",
        "--confirm",
        "--database",
        "sales",
        "--table",
        "orders",
    )
    assert result.exit_code == EXIT_OK
    assert len(seen) == 1
    assert seen[0].name == "orders-rules"
    assert seen[0].database_name == "sales"
    assert seen[0].ruleset == out.read_text(encoding="utf-8")


def test_push_json_reports_what_was_created(
    orders_csv: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import dqdl_gen.push as push_module

    out = tmp_path / "orders.dqdl"
    _run("generate", str(orders_csv), "--out", str(out))
    monkeypatch.setattr(
        push_module,
        "create_ruleset",
        lambda request, client=None: push_module.PushResult(request.name, "us-east-1"),
    )
    payload = json.loads(
        _run("push", str(out), "--name", "orders-rules", "--confirm", "--output", "json").stdout
    )
    assert payload == {"created": "orders-rules", "region": "us-east-1"}


def test_push_reports_a_glue_failure(
    orders_csv: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import dqdl_gen.push as push_module

    out = tmp_path / "orders.dqdl"
    _run("generate", str(orders_csv), "--out", str(out))

    def fail(request: object, client: object | None = None) -> None:
        raise push_module.PushError("a ruleset named 'orders-rules' already exists")

    monkeypatch.setattr(push_module, "create_ruleset", fail)
    result = _run("push", str(out), "--name", "orders-rules", "--confirm")
    assert result.exit_code == EXIT_PUSH_FAILED
    assert "already exists" in result.stderr


def test_push_rejects_a_half_specified_target(orders_csv: Path, tmp_path: Path) -> None:
    out = tmp_path / "orders.dqdl"
    _run("generate", str(orders_csv), "--out", str(out))
    result = _run("push", str(out), "--name", "x", "--confirm", "--database", "sales")
    assert result.exit_code == EXIT_USAGE
    assert "both --database and --table" in (result.stdout + result.stderr).replace("\n", " ")
