"""Generate docs/index.html, the GitHub Pages version of the picker.

The page is built from three inputs: the template in `web/page.html`, the JavaScript engine
in `web/engine.mjs`, and the limits data loaded through the same code path the CLI uses.
Everything is inlined into one self-contained file, so the published page makes no network
requests of any kind and works just as well opened from disk.

    .venv/bin/python scripts/build_page.py            # write ../docs/<tool>/index.html
    .venv/bin/python scripts/build_page.py --check    # fail if it is out of date

`--check` is what stops the committed page drifting away from limits.yaml.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from sagemaker_inference_picker.limits import load_limits
from sagemaker_inference_picker.render import limits_to_dict

#: This tool's own directory.
TOOL_ROOT = Path(__file__).resolve().parent.parent
#: The monorepo root. GitHub Pages serves its docs/ directory, so the generated page
#: has to land there rather than inside this tool's folder.
REPO_ROOT = TOOL_ROOT.parent
TEMPLATE = TOOL_ROOT / "web" / "page.html"
ENGINE = TOOL_ROOT / "web" / "engine.mjs"
OUTPUT = REPO_ROOT / "docs" / "sagemaker-inference-picker" / "index.html"

LIMITS_TOKEN = "/*@@LIMITS@@*/"
ENGINE_TOKEN = "/*@@ENGINE@@*/"

BANNER = "<!-- Generated by scripts/build_page.py from web/page.html, web/engine.mjs and\n"
BANNER += "     src/sagemaker_inference_picker/data/limits.yaml. Do not edit by hand. -->\n"


def build() -> str:
    """Render the page as a single self-contained HTML document."""
    template = TEMPLATE.read_text(encoding="utf-8")
    for token in (LIMITS_TOKEN, ENGINE_TOKEN):
        if token not in template:
            raise SystemExit(f"{TEMPLATE} is missing the {token} placeholder")

    data = json.dumps(limits_to_dict(load_limits()), separators=(",", ":"), sort_keys=True)
    # A literal "</script>" or "<!--" inside a script element would end it early.
    data = data.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")

    page = template.replace(LIMITS_TOKEN, data)
    page = page.replace(ENGINE_TOKEN, ENGINE.read_text(encoding="utf-8").strip())
    return page.replace("<!doctype html>\n", f"<!doctype html>\n{BANNER}", 1)


def main(argv: list[str] | None = None) -> int:
    """Write the page, or check that the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if docs/index.html differs from a fresh build",
    )
    args = parser.parse_args(argv)

    page = build()

    if args.check:
        if not OUTPUT.is_file():
            print(f"{OUTPUT} does not exist; run scripts/build_page.py", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != page:
            print(
                f"{OUTPUT} is out of date with its sources.\nRun: python scripts/build_page.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(REPO_ROOT)} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(page, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(page):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
